name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "🎉 Welcome dev! 🎉\n\nThank you for opening your first issue in my repository! I'm thrilled to have you here. 😊\n\n### Before You Submit\n1. **Title**: Provide a descriptive and concise title for your issue.\n2. **Description**: Clearly explain the problem or feature request.\n3. **Labels**: If applicable, assign appropriate labels to your issue.\n\nOur team will review your issue and provide assistance as needed.\n\nIf you have any questions or need further clarification, feel free to ask. We're here to help you succeed!\n\nHappy coding and thank you for your contribution! 🚀"
        pr-message: "🎉 Welcome dev! 🎉\n\nCongratulations on opening your first pull request in my repository! We're excited to review your changes and collaborate with you. 😊\n\n### Before You Submit\n1. **Fork & Branch**: Fork the repository and create a new branch for your changes.\n2. **Code Style**: Follow our coding style and conventions.\n3. **Tests**: If applicable, ensure your changes include test coverage.\n4. **Description**: Provide a clear description of your changes and why they're valuable.\n\nOur team will review your changes and provide feedback as soon as possible. Be open to suggestions and improvements to your code.\n\nIf you have any questions or need assistance, feel free to ask. We're here to help you succeed!\n\nHappy coding and thank you for your contribution! 🚀"
